/* ==========================================================================
   视频清单 —— 自动生成，请勿手改
   生成脚本：python _build/build_video_index.py
   生成时间：2026-09-23 21:43:10
   --------------------------------------------------------------------------
   视频文件放 videos/<学科>/ 下，跑一次生成脚本就会出现在这里。
   用 JS 而不是 JSON，是为了让 index.html 双击直接打开(file://)时也能读到。
   ========================================================================== */

window.XYB_VIDEOS = {
  generatedAt: "2026-09-23 21:43:10",
  total: 335,
  totalSeconds: 111278,
  subjects: [
    {
      name: "语文", emoji: "📖", color: "#3b82f6",
      count: 108, seconds: 27572,
      series: [
        { name: "63个汉语拼音认读书写", count: 40, seconds: 10369,
          items: [
            { id: "语文/63个汉语拼音认读书写/01-第1集：双姿+四线格+声调符号.mp4", title: "第1集：双姿+四线格+声调符号", file: "../../videos/语文/63个汉语拼音认读书写/01-第1集：双姿+四线格+声调符号.mp4",
              sec: 285, size: 13901254, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/02-第2集：a.mp4", title: "第2集：a", file: "../../videos/语文/63个汉语拼音认读书写/02-第2集：a.mp4",
              sec: 186, size: 7271847, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/03-第3集：o.mp4", title: "第3集：o", file: "../../videos/语文/63个汉语拼音认读书写/03-第3集：o.mp4",
              sec: 139, size: 5583816, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/04-第4集：e.mp4", title: "第4集：e", file: "../../videos/语文/63个汉语拼音认读书写/04-第4集：e.mp4",
              sec: 167, size: 6337146, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/05-第5集：i.mp4", title: "第5集：i", file: "../../videos/语文/63个汉语拼音认读书写/05-第5集：i.mp4",
              sec: 151, size: 6057953, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/06-第6集：u.mp4", title: "第6集：u", file: "../../videos/语文/63个汉语拼音认读书写/06-第6集：u.mp4",
              sec: 163, size: 6295887, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/07-第7集：ü.mp4", title: "第7集：ü", file: "../../videos/语文/63个汉语拼音认读书写/07-第7集：ü.mp4",
              sec: 210, size: 7531294, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/08-第8集：y.mp4", title: "第8集：y", file: "../../videos/语文/63个汉语拼音认读书写/08-第8集：y.mp4",
              sec: 167, size: 6268188, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/09-第9集：yi_yu.mp4", title: "第9集：yi_yu", file: "../../videos/语文/63个汉语拼音认读书写/09-第9集：yi_yu.mp4",
              sec: 255, size: 9844084, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/10-第10集：w_wu.mp4", title: "第10集：w_wu", file: "../../videos/语文/63个汉语拼音认读书写/10-第10集：w_wu.mp4",
              sec: 277, size: 10516550, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/11-第11集：b.mp4", title: "第11集：b", file: "../../videos/语文/63个汉语拼音认读书写/11-第11集：b.mp4",
              sec: 161, size: 5930407, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/12-第12集：p.mp4", title: "第12集：p", file: "../../videos/语文/63个汉语拼音认读书写/12-第12集：p.mp4",
              sec: 169, size: 6288227, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/13-第13集：m.mp4", title: "第13集：m", file: "../../videos/语文/63个汉语拼音认读书写/13-第13集：m.mp4",
              sec: 181, size: 6362585, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/14-第14集：f.mp4", title: "第14集：f", file: "../../videos/语文/63个汉语拼音认读书写/14-第14集：f.mp4",
              sec: 172, size: 6244962, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/15-第15集：d.mp4", title: "第15集：d", file: "../../videos/语文/63个汉语拼音认读书写/15-第15集：d.mp4",
              sec: 177, size: 6614240, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/16-第16集：t.mp4", title: "第16集：t", file: "../../videos/语文/63个汉语拼音认读书写/16-第16集：t.mp4",
              sec: 183, size: 6688214, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/17-第17集：n.mp4", title: "第17集：n", file: "../../videos/语文/63个汉语拼音认读书写/17-第17集：n.mp4",
              sec: 172, size: 6491092, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/18-第18集：l.mp4", title: "第18集：l", file: "../../videos/语文/63个汉语拼音认读书写/18-第18集：l.mp4",
              sec: 112, size: 4568939, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/19-第19集：g.mp4", title: "第19集：g", file: "../../videos/语文/63个汉语拼音认读书写/19-第19集：g.mp4",
              sec: 183, size: 6789759, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/20-第20集：k.mp4", title: "第20集：k", file: "../../videos/语文/63个汉语拼音认读书写/20-第20集：k.mp4",
              sec: 170, size: 6105849, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/21-第21集：h.mp4", title: "第21集：h", file: "../../videos/语文/63个汉语拼音认读书写/21-第21集：h.mp4",
              sec: 181, size: 6606004, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/22-第22集：j.mp4", title: "第22集：j", file: "../../videos/语文/63个汉语拼音认读书写/22-第22集：j.mp4",
              sec: 172, size: 6379596, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/23-第23集：q.mp4", title: "第23集：q", file: "../../videos/语文/63个汉语拼音认读书写/23-第23集：q.mp4",
              sec: 171, size: 6677659, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/24-第24集：x.mp4", title: "第24集：x", file: "../../videos/语文/63个汉语拼音认读书写/24-第24集：x.mp4",
              sec: 170, size: 6948486, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/25-第25集：z_zi.mp4", title: "第25集：z_zi", file: "../../videos/语文/63个汉语拼音认读书写/25-第25集：z_zi.mp4",
              sec: 270, size: 10073310, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/26-第26集：c_ci.mp4", title: "第26集：c_ci", file: "../../videos/语文/63个汉语拼音认读书写/26-第26集：c_ci.mp4",
              sec: 228, size: 9640562, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/27-第27集：s_si.mp4", title: "第27集：s_si", file: "../../videos/语文/63个汉语拼音认读书写/27-第27集：s_si.mp4",
              sec: 278, size: 10814780, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/28-第28集：zh_zhi.mp4", title: "第28集：zh_zhi", file: "../../videos/语文/63个汉语拼音认读书写/28-第28集：zh_zhi.mp4",
              sec: 330, size: 11860987, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/29-第29集：ch_chi.mp4", title: "第29集：ch_chi", file: "../../videos/语文/63个汉语拼音认读书写/29-第29集：ch_chi.mp4",
              sec: 309, size: 11120928, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/30-第30集：sh_shi.mp4", title: "第30集：sh_shi", file: "../../videos/语文/63个汉语拼音认读书写/30-第30集：sh_shi.mp4",
              sec: 347, size: 12367339, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/31-第31集：r_ri.mp4", title: "第31集：r_ri", file: "../../videos/语文/63个汉语拼音认读书写/31-第31集：r_ri.mp4",
              sec: 238, size: 9008776, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/32-第32集：ai_ei_ui.mp4", title: "第32集：ai_ei_ui", file: "../../videos/语文/63个汉语拼音认读书写/32-第32集：ai_ei_ui.mp4",
              sec: 446, size: 15728909, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/33-第33集：ao_ou_iu.mp4", title: "第33集：ao_ou_iu", file: "../../videos/语文/63个汉语拼音认读书写/33-第33集：ao_ou_iu.mp4",
              sec: 403, size: 13932901, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/34-第34集：ie_üe_er.mp4", title: "第34集：ie_üe_er", file: "../../videos/语文/63个汉语拼音认读书写/34-第34集：ie_üe_er.mp4",
              sec: 420, size: 14802520, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/35-第35集：ye_yue.mp4", title: "第35集：ye_yue", file: "../../videos/语文/63个汉语拼音认读书写/35-第35集：ye_yue.mp4",
              sec: 325, size: 12728551, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/36-第36集：an_en.mp4", title: "第36集：an_en", file: "../../videos/语文/63个汉语拼音认读书写/36-第36集：an_en.mp4",
              sec: 303, size: 11161753, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/37-第37集：in_un_ün.mp4", title: "第37集：in_un_ün", file: "../../videos/语文/63个汉语拼音认读书写/37-第37集：in_un_ün.mp4",
              sec: 440, size: 15872982, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/38-第38集：yuan_yin_yun.mp4", title: "第38集：yuan_yin_yun", file: "../../videos/语文/63个汉语拼音认读书写/38-第38集：yuan_yin_yun.mp4",
              sec: 632, size: 22864129, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/39-第39集：ang_eng.mp4", title: "第39集：ang_eng", file: "../../videos/语文/63个汉语拼音认读书写/39-第39集：ang_eng.mp4",
              sec: 431, size: 15705469, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/63个汉语拼音认读书写/40-第40集：ing_ong_ying.mp4", title: "第40集：ing_ong_ying", file: "../../videos/语文/63个汉语拼音认读书写/40-第40集：ing_ong_ying.mp4",
              sec: 595, size: 21467497, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "从文房四宝感受汉字的魅力（免费领）", count: 5, seconds: 1889,
          items: [
            { id: "语文/从文房四宝感受汉字的魅力（免费领）/01-【笔】笔的演变.mp4", title: "【笔】笔的演变", file: "../../videos/语文/从文房四宝感受汉字的魅力（免费领）/01-【笔】笔的演变.mp4",
              sec: 350, size: 76087212, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/从文房四宝感受汉字的魅力（免费领）/02-【墨】不同的墨.mp4", title: "【墨】不同的墨", file: "../../videos/语文/从文房四宝感受汉字的魅力（免费领）/02-【墨】不同的墨.mp4",
              sec: 347, size: 68589052, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/从文房四宝感受汉字的魅力（免费领）/03-【纸】书写材料的进步.mp4", title: "【纸】书写材料的进步", file: "../../videos/语文/从文房四宝感受汉字的魅力（免费领）/03-【纸】书写材料的进步.mp4",
              sec: 395, size: 85650934, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/从文房四宝感受汉字的魅力（免费领）/04-【砚】砚台的制作.mp4", title: "【砚】砚台的制作", file: "../../videos/语文/从文房四宝感受汉字的魅力（免费领）/04-【砚】砚台的制作.mp4",
              sec: 320, size: 41972648, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/从文房四宝感受汉字的魅力（免费领）/05-书法的魅力.mp4", title: "书法的魅力", file: "../../videos/语文/从文房四宝感受汉字的魅力（免费领）/05-书法的魅力.mp4",
              sec: 477, size: 71884562, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "写字十大黄金法则免费领", count: 10, seconds: 1792,
          items: [
            { id: "语文/写字十大黄金法则免费领/01-底横平稳.mp4", title: "底横平稳", file: "../../videos/语文/写字十大黄金法则免费领/01-底横平稳.mp4",
              sec: 220, size: 31516322, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/写字十大黄金法则免费领/02-多捺各异.mp4", title: "多捺各异", file: "../../videos/语文/写字十大黄金法则免费领/02-多捺各异.mp4",
              sec: 171, size: 18517591, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/写字十大黄金法则免费领/03-长短参差.mp4", title: "长短参差", file: "../../videos/语文/写字十大黄金法则免费领/03-长短参差.mp4",
              sec: 154, size: 15731730, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/写字十大黄金法则免费领/04-中直对正.mp4", title: "中直对正", file: "../../videos/语文/写字十大黄金法则免费领/04-中直对正.mp4",
              sec: 163, size: 17166896, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/写字十大黄金法则免费领/05-主笔突出.mp4", title: "主笔突出", file: "../../videos/语文/写字十大黄金法则免费领/05-主笔突出.mp4",
              sec: 182, size: 20684077, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/写字十大黄金法则免费领/06-同形异态.mp4", title: "同形异态", file: "../../videos/语文/写字十大黄金法则免费领/06-同形异态.mp4",
              sec: 168, size: 18325487, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/写字十大黄金法则免费领/07-布白均匀.mp4", title: "布白均匀", file: "../../videos/语文/写字十大黄金法则免费领/07-布白均匀.mp4",
              sec: 162, size: 16572603, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/写字十大黄金法则免费领/08-高低错落.mp4", title: "高低错落", file: "../../videos/语文/写字十大黄金法则免费领/08-高低错落.mp4",
              sec: 161, size: 16501183, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/写字十大黄金法则免费领/09-穿插避让.mp4", title: "穿插避让", file: "../../videos/语文/写字十大黄金法则免费领/09-穿插避让.mp4",
              sec: 183, size: 18824433, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/写字十大黄金法则免费领/10-正斜相成.mp4", title: "正斜相成", file: "../../videos/语文/写字十大黄金法则免费领/10-正斜相成.mp4",
              sec: 228, size: 26575768, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "古诗故事会免费领", count: 20, seconds: 5691,
          items: [
            { id: "语文/古诗故事会免费领/01-咏鹅.mp4", title: "咏鹅", file: "../../videos/语文/古诗故事会免费领/01-咏鹅.mp4",
              sec: 263, size: 18037462, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/02-悯农（其二）.mp4", title: "悯农（其二）", file: "../../videos/语文/古诗故事会免费领/02-悯农（其二）.mp4",
              sec: 264, size: 19681700, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/03-春晓.mp4", title: "春晓", file: "../../videos/语文/古诗故事会免费领/03-春晓.mp4",
              sec: 253, size: 18652291, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/04-赠汪伦.mp4", title: "赠汪伦", file: "../../videos/语文/古诗故事会免费领/04-赠汪伦.mp4",
              sec: 250, size: 21164554, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/05-望庐山瀑布.mp4", title: "望庐山瀑布", file: "../../videos/语文/古诗故事会免费领/05-望庐山瀑布.mp4",
              sec: 252, size: 19640408, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/06-江雪.mp4", title: "江雪", file: "../../videos/语文/古诗故事会免费领/06-江雪.mp4",
              sec: 279, size: 22869425, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/07-梅花.mp4", title: "梅花", file: "../../videos/语文/古诗故事会免费领/07-梅花.mp4",
              sec: 307, size: 20634686, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/08-咏柳.mp4", title: "咏柳", file: "../../videos/语文/古诗故事会免费领/08-咏柳.mp4",
              sec: 303, size: 25221193, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/09-村居.mp4", title: "村居", file: "../../videos/语文/古诗故事会免费领/09-村居.mp4",
              sec: 282, size: 24510400, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/10-晓出净慈寺送林子方.mp4", title: "晓出净慈寺送林子方", file: "../../videos/语文/古诗故事会免费领/10-晓出净慈寺送林子方.mp4",
              sec: 255, size: 21278684, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/11-望天门山.mp4", title: "望天门山", file: "../../videos/语文/古诗故事会免费领/11-望天门山.mp4",
              sec: 303, size: 22522247, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/12-早发白帝城.mp4", title: "早发白帝城", file: "../../videos/语文/古诗故事会免费领/12-早发白帝城.mp4",
              sec: 282, size: 22330111, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/13-饮湖上初晴后雨.mp4", title: "饮湖上初晴后雨", file: "../../videos/语文/古诗故事会免费领/13-饮湖上初晴后雨.mp4",
              sec: 328, size: 26564524, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/14-绝句（迟日江山丽）.mp4", title: "绝句（迟日江山丽）", file: "../../videos/语文/古诗故事会免费领/14-绝句（迟日江山丽）.mp4",
              sec: 245, size: 18906865, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/15-鹿柴.mp4", title: "鹿柴", file: "../../videos/语文/古诗故事会免费领/15-鹿柴.mp4",
              sec: 309, size: 21900913, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/16-九月九日忆山东兄弟.mp4", title: "九月九日忆山东兄弟", file: "../../videos/语文/古诗故事会免费领/16-九月九日忆山东兄弟.mp4",
              sec: 292, size: 21896871, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/17-惠崇春江晚景.mp4", title: "惠崇春江晚景", file: "../../videos/语文/古诗故事会免费领/17-惠崇春江晚景.mp4",
              sec: 280, size: 21261115, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/18-元日.mp4", title: "元日", file: "../../videos/语文/古诗故事会免费领/18-元日.mp4",
              sec: 331, size: 23744579, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/19-山行.mp4", title: "山行", file: "../../videos/语文/古诗故事会免费领/19-山行.mp4",
              sec: 284, size: 20606682, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/古诗故事会免费领/20-题西林壁.mp4", title: "题西林壁", file: "../../videos/语文/古诗故事会免费领/20-题西林壁.mp4",
              sec: 329, size: 23076123, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "文学启蒙（免费领）", count: 10, seconds: 1268,
          items: [
            { id: "语文/文学启蒙（免费领）/01-寻隐者不遇.mp4", title: "寻隐者不遇", file: "../../videos/语文/文学启蒙（免费领）/01-寻隐者不遇.mp4",
              sec: 53, size: 3128562, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/文学启蒙（免费领）/02-望庐山瀑布.mp4", title: "望庐山瀑布", file: "../../videos/语文/文学启蒙（免费领）/02-望庐山瀑布.mp4",
              sec: 69, size: 4565605, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/文学启蒙（免费领）/03-赠汪伦.mp4", title: "赠汪伦", file: "../../videos/语文/文学启蒙（免费领）/03-赠汪伦.mp4",
              sec: 64, size: 4537580, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/文学启蒙（免费领）/04-画.mp4", title: "画", file: "../../videos/语文/文学启蒙（免费领）/04-画.mp4",
              sec: 60, size: 3871830, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/文学启蒙（免费领）/05-赋得古原草送别（节选）.mp4", title: "赋得古原草送别（节选）", file: "../../videos/语文/文学启蒙（免费领）/05-赋得古原草送别（节选）.mp4",
              sec: 71, size: 4867940, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/文学启蒙（免费领）/06-郑人买履.mp4", title: "郑人买履", file: "../../videos/语文/文学启蒙（免费领）/06-郑人买履.mp4",
              sec: 200, size: 13892579, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/文学启蒙（免费领）/07-水滴石穿.mp4", title: "水滴石穿", file: "../../videos/语文/文学启蒙（免费领）/07-水滴石穿.mp4",
              sec: 190, size: 10742878, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/文学启蒙（免费领）/08-自相矛盾.mp4", title: "自相矛盾", file: "../../videos/语文/文学启蒙（免费领）/08-自相矛盾.mp4",
              sec: 167, size: 11653881, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/文学启蒙（免费领）/09-买椟还珠.mp4", title: "买椟还珠", file: "../../videos/语文/文学启蒙（免费领）/09-买椟还珠.mp4",
              sec: 189, size: 14417610, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/文学启蒙（免费领）/10-黔驴技穷.mp4", title: "黔驴技穷", file: "../../videos/语文/文学启蒙（免费领）/10-黔驴技穷.mp4",
              sec: 205, size: 14900311, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "汉字书写训练免费领", count: 10, seconds: 2023,
          items: [
            { id: "语文/汉字书写训练免费领/01-横直线控笔学写长横.mp4", title: "横直线控笔学写长横", file: "../../videos/语文/汉字书写训练免费领/01-横直线控笔学写长横.mp4",
              sec: 257, size: 12496657, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/汉字书写训练免费领/02-竖直线控笔学写垂露竖.mp4", title: "竖直线控笔学写垂露竖", file: "../../videos/语文/汉字书写训练免费领/02-竖直线控笔学写垂露竖.mp4",
              sec: 196, size: 9928076, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/汉字书写训练免费领/03-左斜线控笔学写斜撇.mp4", title: "左斜线控笔学写斜撇", file: "../../videos/语文/汉字书写训练免费领/03-左斜线控笔学写斜撇.mp4",
              sec: 182, size: 9797981, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/汉字书写训练免费领/04-右斜线控笔学写斜捺.mp4", title: "右斜线控笔学写斜捺", file: "../../videos/语文/汉字书写训练免费领/04-右斜线控笔学写斜捺.mp4",
              sec: 176, size: 9300627, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/汉字书写训练免费领/05-直角折线控笔学写横折.mp4", title: "直角折线控笔学写横折", file: "../../videos/语文/汉字书写训练免费领/05-直角折线控笔学写横折.mp4",
              sec: 218, size: 10947787, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/汉字书写训练免费领/06-直角折线控笔学写竖折.mp4", title: "直角折线控笔学写竖折", file: "../../videos/语文/汉字书写训练免费领/06-直角折线控笔学写竖折.mp4",
              sec: 217, size: 10620276, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/汉字书写训练免费领/07-回形线控笔学写横折钩.mp4", title: "回形线控笔学写横折钩", file: "../../videos/语文/汉字书写训练免费领/07-回形线控笔学写横折钩.mp4",
              sec: 180, size: 9118755, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/汉字书写训练免费领/08-回形线控笔学写竖弯钩.mp4", title: "回形线控笔学写竖弯钩", file: "../../videos/语文/汉字书写训练免费领/08-回形线控笔学写竖弯钩.mp4",
              sec: 202, size: 10135070, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/汉字书写训练免费领/09-弧线控笔学写斜钩.mp4", title: "弧线控笔学写斜钩", file: "../../videos/语文/汉字书写训练免费领/09-弧线控笔学写斜钩.mp4",
              sec: 196, size: 9770311, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/汉字书写训练免费领/10-蜗牛曲线控笔学写卧钩.mp4", title: "蜗牛曲线控笔学写卧钩", file: "../../videos/语文/汉字书写训练免费领/10-蜗牛曲线控笔学写卧钩.mp4",
              sec: 199, size: 10357276, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "童话主题故事免费领", count: 4, seconds: 1340,
          items: [
            { id: "语文/童话主题故事免费领/01-Cinderella.mp4", title: "Cinderella", file: "../../videos/语文/童话主题故事免费领/01-Cinderella.mp4",
              sec: 341, size: 27448830, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/童话主题故事免费领/02-Snow White.mp4", title: "Snow White", file: "../../videos/语文/童话主题故事免费领/02-Snow White.mp4",
              sec: 334, size: 23253006, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/童话主题故事免费领/03-The Frog Prince.mp4", title: "The Frog Prince", file: "../../videos/语文/童话主题故事免费领/03-The Frog Prince.mp4",
              sec: 381, size: 30827745, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/童话主题故事免费领/04-The Adventures of Princess.mp4", title: "The Adventures of Princess", file: "../../videos/语文/童话主题故事免费领/04-The Adventures of Princess.mp4",
              sec: 284, size: 26626502, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "童话故事新编（免费领）", count: 5, seconds: 1621,
          items: [
            { id: "语文/童话故事新编（免费领）/01-The Ugly Duckling.mp4", title: "The Ugly Duckling", file: "../../videos/语文/童话故事新编（免费领）/01-The Ugly Duckling.mp4",
              sec: 319, size: 21053056, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/童话故事新编（免费领）/02-The Turtle and the Rabbit.mp4", title: "The Turtle and the Rabbit", file: "../../videos/语文/童话故事新编（免费领）/02-The Turtle and the Rabbit.mp4",
              sec: 310, size: 23812997, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/童话故事新编（免费领）/03-The Boy Who Cried Wolf.mp4", title: "The Boy Who Cried Wolf", file: "../../videos/语文/童话故事新编（免费领）/03-The Boy Who Cried Wolf.mp4",
              sec: 287, size: 20790155, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/童话故事新编（免费领）/04-The Three Little Pigs.mp4", title: "The Three Little Pigs", file: "../../videos/语文/童话故事新编（免费领）/04-The Three Little Pigs.mp4",
              sec: 364, size: 32742224, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/童话故事新编（免费领）/05-The King's New Robe.mp4", title: "The King's New Robe", file: "../../videos/语文/童话故事新编（免费领）/05-The King's New Robe.mp4",
              sec: 341, size: 25586611, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "阅读启蒙小剧场免费领", count: 4, seconds: 1579,
          items: [
            { id: "语文/阅读启蒙小剧场免费领/01-小儿垂钓.mp4", title: "小儿垂钓", file: "../../videos/语文/阅读启蒙小剧场免费领/01-小儿垂钓.mp4",
              sec: 409, size: 33849762, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/阅读启蒙小剧场免费领/02-缘木求鱼.mp4", title: "缘木求鱼", file: "../../videos/语文/阅读启蒙小剧场免费领/02-缘木求鱼.mp4",
              sec: 373, size: 29866973, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/阅读启蒙小剧场免费领/03-三天打鱼，两天晒网.mp4", title: "三天打鱼，两天晒网", file: "../../videos/语文/阅读启蒙小剧场免费领/03-三天打鱼，两天晒网.mp4",
              sec: 384, size: 36295262, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "语文/阅读启蒙小剧场免费领/04-白夫子减肥记.mp4", title: "白夫子减肥记", file: "../../videos/语文/阅读启蒙小剧场免费领/04-白夫子减肥记.mp4",
              sec: 413, size: 34189025, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        }
      ]
    },
    {
      name: "数学", emoji: "➗", color: "#f59e0b",
      count: 18, seconds: 10005,
      series: [
        { name: "100以内加减法免费领", count: 10, seconds: 5771,
          items: [
            { id: "数学/100以内加减法免费领/01-甜品派对.mp4", title: "甜品派对", file: "../../videos/数学/100以内加减法免费领/01-甜品派对.mp4",
              sec: 528, size: 23072844, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/100以内加减法免费领/02-小演员请就位.mp4", title: "小演员请就位", file: "../../videos/数学/100以内加减法免费领/02-小演员请就位.mp4",
              sec: 605, size: 30322491, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/100以内加减法免费领/03-巧克力爆发啦.mp4", title: "巧克力爆发啦", file: "../../videos/数学/100以内加减法免费领/03-巧克力爆发啦.mp4",
              sec: 529, size: 24135778, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/100以内加减法免费领/04-造雪大作战.mp4", title: "造雪大作战", file: "../../videos/数学/100以内加减法免费领/04-造雪大作战.mp4",
              sec: 536, size: 27250125, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/100以内加减法免费领/05-废品回收机.mp4", title: "废品回收机", file: "../../videos/数学/100以内加减法免费领/05-废品回收机.mp4",
              sec: 736, size: 36507312, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/100以内加减法免费领/06-会旋转的风筝.mp4", title: "会旋转的风筝", file: "../../videos/数学/100以内加减法免费领/06-会旋转的风筝.mp4",
              sec: 610, size: 25687707, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/100以内加减法免费领/07-暴雨大作战.mp4", title: "暴雨大作战", file: "../../videos/数学/100以内加减法免费领/07-暴雨大作战.mp4",
              sec: 559, size: 25223096, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/100以内加减法免费领/08-山羊爷爷的树屋.mp4", title: "山羊爷爷的树屋", file: "../../videos/数学/100以内加减法免费领/08-山羊爷爷的树屋.mp4",
              sec: 492, size: 24355732, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/100以内加减法免费领/09-神秘的小帮手.mp4", title: "神秘的小帮手", file: "../../videos/数学/100以内加减法免费领/09-神秘的小帮手.mp4",
              sec: 490, size: 23145447, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/100以内加减法免费领/10-趣味运动会.mp4", title: "趣味运动会", file: "../../videos/数学/100以内加减法免费领/10-趣味运动会.mp4",
              sec: 686, size: 32889431, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "分类与统计免费领", count: 4, seconds: 2066,
          items: [
            { id: "数学/分类与统计免费领/01-思维小乐队.mp4", title: "思维小乐队", file: "../../videos/数学/分类与统计免费领/01-思维小乐队.mp4",
              sec: 471, size: 26569197, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/分类与统计免费领/02-多味蛋糕.mp4", title: "多味蛋糕", file: "../../videos/数学/分类与统计免费领/02-多味蛋糕.mp4",
              sec: 595, size: 28330051, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/分类与统计免费领/03-水果运输记.mp4", title: "水果运输记", file: "../../videos/数学/分类与统计免费领/03-水果运输记.mp4",
              sec: 522, size: 26909059, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/分类与统计免费领/04-旅行家豆豆鼠.mp4", title: "旅行家豆豆鼠", file: "../../videos/数学/分类与统计免费领/04-旅行家豆豆鼠.mp4",
              sec: 478, size: 25335902, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "每天10分钟，吃透单双数免费领", count: 4, seconds: 2168,
          items: [
            { id: "数学/每天10分钟，吃透单双数免费领/01-10以内单双数.mp4", title: "10以内单双数", file: "../../videos/数学/每天10分钟，吃透单双数免费领/01-10以内单双数.mp4",
              sec: 551, size: 30991265, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/每天10分钟，吃透单双数免费领/02-复杂单双数.mp4", title: "复杂单双数", file: "../../videos/数学/每天10分钟，吃透单双数免费领/02-复杂单双数.mp4",
              sec: 584, size: 26303255, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/每天10分钟，吃透单双数免费领/03-单双数的正向应用.mp4", title: "单双数的正向应用", file: "../../videos/数学/每天10分钟，吃透单双数免费领/03-单双数的正向应用.mp4",
              sec: 516, size: 26901834, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "数学/每天10分钟，吃透单双数免费领/04-单双数的逆向应用.mp4", title: "单双数的逆向应用", file: "../../videos/数学/每天10分钟，吃透单双数免费领/04-单双数的逆向应用.mp4",
              sec: 517, size: 29542684, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        }
      ]
    },
    {
      name: "英语", emoji: "🔤", color: "#10b981",
      count: 49, seconds: 15324,
      series: [
        { name: "免费领5节英语学习包", count: 5, seconds: 2311,
          items: [
            { id: "英语/免费领5节英语学习包/01-The Red Liquid.mp4", title: "The Red Liquid", file: "../../videos/英语/免费领5节英语学习包/01-The Red Liquid.mp4",
              sec: 327, size: 26571427, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/免费领5节英语学习包/02-I Want to Sing!.mp4", title: "I Want to Sing!", file: "../../videos/英语/免费领5节英语学习包/02-I Want to Sing!.mp4",
              sec: 356, size: 28854076, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/免费领5节英语学习包/03-A Delicious Lunch.mp4", title: "A Delicious Lunch", file: "../../videos/英语/免费领5节英语学习包/03-A Delicious Lunch.mp4",
              sec: 374, size: 29663123, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/免费领5节英语学习包/04-The Blue Liquid.mp4", title: "The Blue Liquid", file: "../../videos/英语/免费领5节英语学习包/04-The Blue Liquid.mp4",
              sec: 357, size: 27462693, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/免费领5节英语学习包/05-It's Saturday!.mp4", title: "It's Saturday!", file: "../../videos/英语/免费领5节英语学习包/05-It's Saturday!.mp4",
              sec: 897, size: 64175396, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "全英探秘恐龙世界免费领", count: 4, seconds: 1053,
          items: [
            { id: "英语/全英探秘恐龙世界免费领/01-Dinosaurs! Dinosaurs!.mp4", title: "Dinosaurs! Dinosaurs!", file: "../../videos/英语/全英探秘恐龙世界免费领/01-Dinosaurs! Dinosaurs!.mp4",
              sec: 266, size: 21438700, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/全英探秘恐龙世界免费领/02-The Little Dinosaur.mp4", title: "The Little Dinosaur", file: "../../videos/英语/全英探秘恐龙世界免费领/02-The Little Dinosaur.mp4",
              sec: 240, size: 19583655, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/全英探秘恐龙世界免费领/03-Are You My Mother_.mp4", title: "Are You My Mother_", file: "../../videos/英语/全英探秘恐龙世界免费领/03-Are You My Mother_.mp4",
              sec: 286, size: 25484436, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/全英探秘恐龙世界免费领/04-Bye, Little Dinosaur!.mp4", title: "Bye, Little Dinosaur!", file: "../../videos/英语/全英探秘恐龙世界免费领/04-Bye, Little Dinosaur!.mp4",
              sec: 261, size: 23917147, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "全英探索科学奥秘免费领", count: 5, seconds: 1630,
          items: [
            { id: "英语/全英探索科学奥秘免费领/01-D1-The Rubber Duck.mp4", title: "D1-The Rubber Duck", file: "../../videos/英语/全英探索科学奥秘免费领/01-D1-The Rubber Duck.mp4",
              sec: 321, size: 24004503, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/全英探索科学奥秘免费领/02-D2-The Magnet.mp4", title: "D2-The Magnet", file: "../../videos/英语/全英探索科学奥秘免费领/02-D2-The Magnet.mp4",
              sec: 340, size: 24502937, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/全英探索科学奥秘免费领/03-D3-What Is That_.mp4", title: "D3-What Is That_", file: "../../videos/英语/全英探索科学奥秘免费领/03-D3-What Is That_.mp4",
              sec: 261, size: 18821197, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/全英探索科学奥秘免费领/04-D4-Keeping Things Dry.mp4", title: "D4-Keeping Things Dry", file: "../../videos/英语/全英探索科学奥秘免费领/04-D4-Keeping Things Dry.mp4",
              sec: 332, size: 26195761, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/全英探索科学奥秘免费领/05-D5-Magic Colors.mp4", title: "D5-Magic Colors", file: "../../videos/英语/全英探索科学奥秘免费领/05-D5-Magic Colors.mp4",
              sec: 376, size: 27115920, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "思维导图记单词免费领", count: 7, seconds: 2178,
          items: [
            { id: "英语/思维导图记单词免费领/01-The Lost Newt.mp4", title: "The Lost Newt", file: "../../videos/英语/思维导图记单词免费领/01-The Lost Newt.mp4",
              sec: 387, size: 29436969, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/思维导图记单词免费领/02-Changing Colors.mp4", title: "Changing Colors", file: "../../videos/英语/思维导图记单词免费领/02-Changing Colors.mp4",
              sec: 293, size: 21060292, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/思维导图记单词免费领/03-Breakfast Time.mp4", title: "Breakfast Time", file: "../../videos/英语/思维导图记单词免费领/03-Breakfast Time.mp4",
              sec: 296, size: 21684458, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/思维导图记单词免费领/04-Let's Travel!.mp4", title: "Let's Travel!", file: "../../videos/英语/思维导图记单词免费领/04-Let's Travel!.mp4",
              sec: 323, size: 22693120, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/思维导图记单词免费领/05-The Family Tree.mp4", title: "The Family Tree", file: "../../videos/英语/思维导图记单词免费领/05-The Family Tree.mp4",
              sec: 330, size: 26816440, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/思维导图记单词免费领/06-Let's Party!.mp4", title: "Let's Party!", file: "../../videos/英语/思维导图记单词免费领/06-Let's Party!.mp4",
              sec: 263, size: 19670056, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/思维导图记单词免费领/07-A Day with Luke.mp4", title: "A Day with Luke", file: "../../videos/英语/思维导图记单词免费领/07-A Day with Luke.mp4",
              sec: 286, size: 22244618, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "玩转100+动物主题单词免费领", count: 6, seconds: 2162,
          items: [
            { id: "英语/玩转100+动物主题单词免费领/01-Marine Animals.mp4", title: "Marine Animals", file: "../../videos/英语/玩转100+动物主题单词免费领/01-Marine Animals.mp4",
              sec: 250, size: 30399020, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/玩转100+动物主题单词免费领/02-Insects.mp4", title: "Insects", file: "../../videos/英语/玩转100+动物主题单词免费领/02-Insects.mp4",
              sec: 266, size: 43023133, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/玩转100+动物主题单词免费领/03-Farm Animals.mp4", title: "Farm Animals", file: "../../videos/英语/玩转100+动物主题单词免费领/03-Farm Animals.mp4",
              sec: 281, size: 43757980, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/玩转100+动物主题单词免费领/04-Wild Animals.mp4", title: "Wild Animals", file: "../../videos/英语/玩转100+动物主题单词免费领/04-Wild Animals.mp4",
              sec: 244, size: 53568654, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/玩转100+动物主题单词免费领/05-Animal Hunt.mp4", title: "Animal Hunt", file: "../../videos/英语/玩转100+动物主题单词免费领/05-Animal Hunt.mp4",
              sec: 609, size: 52329736, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/玩转100+动物主题单词免费领/06-Animal Vocabulary.mp4", title: "Animal Vocabulary", file: "../../videos/英语/玩转100+动物主题单词免费领/06-Animal Vocabulary.mp4",
              sec: 512, size: 15964247, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "纯英·动物王国大冒险免费领", count: 8, seconds: 2642,
          items: [
            { id: "英语/纯英·动物王国大冒险免费领/01-Moo!.mp4", title: "Moo!", file: "../../videos/英语/纯英·动物王国大冒险免费领/01-Moo!.mp4",
              sec: 292, size: 23941974, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/纯英·动物王国大冒险免费领/02-Mouse and Dog.mp4", title: "Mouse and Dog", file: "../../videos/英语/纯英·动物王国大冒险免费领/02-Mouse and Dog.mp4",
              sec: 314, size: 23901030, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/纯英·动物王国大冒险免费领/03-Where Is Mouse_.mp4", title: "Where Is Mouse_", file: "../../videos/英语/纯英·动物王国大冒险免费领/03-Where Is Mouse_.mp4",
              sec: 308, size: 23824560, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/纯英·动物王国大冒险免费领/04-The Show.mp4", title: "The Show", file: "../../videos/英语/纯英·动物王国大冒险免费领/04-The Show.mp4",
              sec: 305, size: 22542181, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/纯英·动物王国大冒险免费领/05-Helping the Crabs.mp4", title: "Helping the Crabs", file: "../../videos/英语/纯英·动物王国大冒险免费领/05-Helping the Crabs.mp4",
              sec: 381, size: 30323567, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/纯英·动物王国大冒险免费领/06-Looking for the Sea Lion.mp4", title: "Looking for the Sea Lion", file: "../../videos/英语/纯英·动物王国大冒险免费领/06-Looking for the Sea Lion.mp4",
              sec: 332, size: 25026613, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/纯英·动物王国大冒险免费领/07-Helping the Seahorse.mp4", title: "Helping the Seahorse", file: "../../videos/英语/纯英·动物王国大冒险免费领/07-Helping the Seahorse.mp4",
              sec: 369, size: 30674581, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/纯英·动物王国大冒险免费领/08-The Storm.mp4", title: "The Storm", file: "../../videos/英语/纯英·动物王国大冒险免费领/08-The Storm.mp4",
              sec: 341, size: 27409453, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "英语口语天天练免费领", count: 10, seconds: 2258,
          items: [
            { id: "英语/英语口语天天练免费领/01-Good Morning!.mp4", title: "Good Morning!", file: "../../videos/英语/英语口语天天练免费领/01-Good Morning!.mp4",
              sec: 217, size: 16202233, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语口语天天练免费领/02-How Are You_.mp4", title: "How Are You_", file: "../../videos/英语/英语口语天天练免费领/02-How Are You_.mp4",
              sec: 197, size: 16726425, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语口语天天练免费领/03-Thank You!.mp4", title: "Thank You!", file: "../../videos/英语/英语口语天天练免费领/03-Thank You!.mp4",
              sec: 211, size: 17576468, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语口语天天练免费领/04-At the Zoo.mp4", title: "At the Zoo", file: "../../videos/英语/英语口语天天练免费领/04-At the Zoo.mp4",
              sec: 229, size: 19615834, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语口语天天练免费领/05-I'm So Sorry!.mp4", title: "I'm So Sorry!", file: "../../videos/英语/英语口语天天练免费领/05-I'm So Sorry!.mp4",
              sec: 218, size: 18433158, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语口语天天练免费领/06-Happy Weekend!.mp4", title: "Happy Weekend!", file: "../../videos/英语/英语口语天天练免费领/06-Happy Weekend!.mp4",
              sec: 208, size: 19584562, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语口语天天练免费领/07-Our Town.mp4", title: "Our Town", file: "../../videos/英语/英语口语天天练免费领/07-Our Town.mp4",
              sec: 226, size: 23362604, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语口语天天练免费领/08-Yummy! Yummy!.mp4", title: "Yummy! Yummy!", file: "../../videos/英语/英语口语天天练免费领/08-Yummy! Yummy!.mp4",
              sec: 246, size: 21003798, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语口语天天练免费领/09-Amazing Nature.mp4", title: "Amazing Nature", file: "../../videos/英语/英语口语天天练免费领/09-Amazing Nature.mp4",
              sec: 247, size: 22100920, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语口语天天练免费领/10-Let's Go Shopping!.mp4", title: "Let's Go Shopping!", file: "../../videos/英语/英语口语天天练免费领/10-Let's Go Shopping!.mp4",
              sec: 259, size: 22159944, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "英语美食单词免费领", count: 4, seconds: 1090,
          items: [
            { id: "英语/英语美食单词免费领/01-Helping Miss Cat.mp4", title: "Helping Miss Cat", file: "../../videos/英语/英语美食单词免费领/01-Helping Miss Cat.mp4",
              sec: 250, size: 21027601, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语美食单词免费领/02-Cookies and Pizzas.mp4", title: "Cookies and Pizzas", file: "../../videos/英语/英语美食单词免费领/02-Cookies and Pizzas.mp4",
              sec: 320, size: 27497201, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语美食单词免费领/03-The Milk.mp4", title: "The Milk", file: "../../videos/英语/英语美食单词免费领/03-The Milk.mp4",
              sec: 266, size: 23727127, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "英语/英语美食单词免费领/04-The Store.mp4", title: "The Store", file: "../../videos/英语/英语美食单词免费领/04-The Store.mp4",
              sec: 254, size: 21680354, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        }
      ]
    },
    {
      name: "思维", emoji: "🧩", color: "#7c6cf5",
      count: 28, seconds: 11847,
      series: [
        { name: "0基础魔方训练免费领", count: 8, seconds: 3725,
          items: [
            { id: "思维/0基础魔方训练免费领/01-误入魔方世界.mp4", title: "误入魔方世界", file: "../../videos/思维/0基础魔方训练免费领/01-误入魔方世界.mp4",
              sec: 489, size: 22031621, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/0基础魔方训练免费领/02-森林大冒险.mp4", title: "森林大冒险", file: "../../videos/思维/0基础魔方训练免费领/02-森林大冒险.mp4",
              sec: 533, size: 23308274, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/0基础魔方训练免费领/03-白色小船.mp4", title: "白色小船", file: "../../videos/思维/0基础魔方训练免费领/03-白色小船.mp4",
              sec: 393, size: 17762547, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/0基础魔方训练免费领/04-搭楼梯.mp4", title: "搭楼梯", file: "../../videos/思维/0基础魔方训练免费领/04-搭楼梯.mp4",
              sec: 544, size: 29093029, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/0基础魔方训练免费领/05-光束电梯.mp4", title: "光束电梯", file: "../../videos/思维/0基础魔方训练免费领/05-光束电梯.mp4",
              sec: 341, size: 15495530, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/0基础魔方训练免费领/06-奇怪的方格.mp4", title: "奇怪的方格", file: "../../videos/思维/0基础魔方训练免费领/06-奇怪的方格.mp4",
              sec: 493, size: 24450798, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/0基础魔方训练免费领/07-隐形碎片.mp4", title: "隐形碎片", file: "../../videos/思维/0基础魔方训练免费领/07-隐形碎片.mp4",
              sec: 506, size: 22497966, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/0基础魔方训练免费领/08-重获生机.mp4", title: "重获生机", file: "../../videos/思维/0基础魔方训练免费领/08-重获生机.mp4",
              sec: 426, size: 23997383, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "初级围棋入门免费领", count: 10, seconds: 2913,
          items: [
            { id: "思维/初级围棋入门免费领/01-一起下围棋.mp4", title: "一起下围棋", file: "../../videos/思维/初级围棋入门免费领/01-一起下围棋.mp4",
              sec: 322, size: 20697758, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/初级围棋入门免费领/02-会呼吸的棋子.mp4", title: "会呼吸的棋子", file: "../../videos/思维/初级围棋入门免费领/02-会呼吸的棋子.mp4",
              sec: 350, size: 18272023, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/初级围棋入门免费领/03-棋盘上的断点.mp4", title: "棋盘上的断点", file: "../../videos/思维/初级围棋入门免费领/03-棋盘上的断点.mp4",
              sec: 273, size: 13989666, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/初级围棋入门免费领/04-金角银边草肚皮.mp4", title: "金角银边草肚皮", file: "../../videos/思维/初级围棋入门免费领/04-金角银边草肚皮.mp4",
              sec: 336, size: 20739520, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/初级围棋入门免费领/05-禁入点.mp4", title: "禁入点", file: "../../videos/思维/初级围棋入门免费领/05-禁入点.mp4",
              sec: 258, size: 14916053, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/初级围棋入门免费领/06-吃子方法.mp4", title: "吃子方法", file: "../../videos/思维/初级围棋入门免费领/06-吃子方法.mp4",
              sec: 272, size: 16101161, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/初级围棋入门免费领/07-棋子的保卫战.mp4", title: "棋子的保卫战", file: "../../videos/思维/初级围棋入门免费领/07-棋子的保卫战.mp4",
              sec: 272, size: 17500172, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/初级围棋入门免费领/08-两眼活棋.mp4", title: "两眼活棋", file: "../../videos/思维/初级围棋入门免费领/08-两眼活棋.mp4",
              sec: 298, size: 17879779, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/初级围棋入门免费领/09-地盘攻防.mp4", title: "地盘攻防", file: "../../videos/思维/初级围棋入门免费领/09-地盘攻防.mp4",
              sec: 260, size: 16271396, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/初级围棋入门免费领/10-收官和判定胜负.mp4", title: "收官和判定胜负", file: "../../videos/思维/初级围棋入门免费领/10-收官和判定胜负.mp4",
              sec: 272, size: 18903310, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "思维能力训练免费领", count: 5, seconds: 2663,
          items: [
            { id: "思维/思维能力训练免费领/01-超级大的南瓜屋.mp4", title: "超级大的南瓜屋", file: "../../videos/思维/思维能力训练免费领/01-超级大的南瓜屋.mp4",
              sec: 464, size: 23275872, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/思维能力训练免费领/02-小小粉刷匠.mp4", title: "小小粉刷匠", file: "../../videos/思维/思维能力训练免费领/02-小小粉刷匠.mp4",
              sec: 503, size: 21403457, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/思维能力训练免费领/03-扭扭踢踏舞.mp4", title: "扭扭踢踏舞", file: "../../videos/思维/思维能力训练免费领/03-扭扭踢踏舞.mp4",
              sec: 488, size: 23819694, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/思维能力训练免费领/04-小小木偶表演家.mp4", title: "小小木偶表演家", file: "../../videos/思维/思维能力训练免费领/04-小小木偶表演家.mp4",
              sec: 434, size: 24387554, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/思维能力训练免费领/05-糖果大冒险.mp4", title: "糖果大冒险", file: "../../videos/思维/思维能力训练免费领/05-糖果大冒险.mp4",
              sec: 774, size: 43251542, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "逻辑推理训练免费领", count: 5, seconds: 2546,
          items: [
            { id: "思维/逻辑推理训练免费领/01-发光的铃铛花.mp4", title: "发光的铃铛花", file: "../../videos/思维/逻辑推理训练免费领/01-发光的铃铛花.mp4",
              sec: 533, size: 23522988, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/逻辑推理训练免费领/02-玩偶洗刷刷.mp4", title: "玩偶洗刷刷", file: "../../videos/思维/逻辑推理训练免费领/02-玩偶洗刷刷.mp4",
              sec: 455, size: 21507960, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/逻辑推理训练免费领/03-侦探小队.mp4", title: "侦探小队", file: "../../videos/思维/逻辑推理训练免费领/03-侦探小队.mp4",
              sec: 478, size: 24979670, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/逻辑推理训练免费领/04-积木小骑士.mp4", title: "积木小骑士", file: "../../videos/思维/逻辑推理训练免费领/04-积木小骑士.mp4",
              sec: 462, size: 26684292, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "思维/逻辑推理训练免费领/05-果蔬游乐园.mp4", title: "果蔬游乐园", file: "../../videos/思维/逻辑推理训练免费领/05-果蔬游乐园.mp4",
              sec: 618, size: 35044211, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        }
      ]
    },
    {
      name: "科学", emoji: "🔬", color: "#06b6d4",
      count: 21, seconds: 8459,
      series: [
        { name: "科学探索小游戏免费领", count: 15, seconds: 4511,
          items: [
            { id: "科学/科学探索小游戏免费领/01-毛毛虫赛跑.mp4", title: "毛毛虫赛跑", file: "../../videos/科学/科学探索小游戏免费领/01-毛毛虫赛跑.mp4",
              sec: 284, size: 22934007, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/02-神奇的纸桥.mp4", title: "神奇的纸桥", file: "../../videos/科学/科学探索小游戏免费领/02-神奇的纸桥.mp4",
              sec: 362, size: 26772471, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/03-穿越A4纸.mp4", title: "穿越A4纸", file: "../../videos/科学/科学探索小游戏免费领/03-穿越A4纸.mp4",
              sec: 340, size: 34488430, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/04-嘿！把彩虹装进杯子里.mp4", title: "嘿！把彩虹装进杯子里", file: "../../videos/科学/科学探索小游戏免费领/04-嘿！把彩虹装进杯子里.mp4",
              sec: 238, size: 19596818, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/05-小鱼游起来.mp4", title: "小鱼游起来", file: "../../videos/科学/科学探索小游戏免费领/05-小鱼游起来.mp4",
              sec: 400, size: 29113294, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/06-魔法药水.mp4", title: "魔法药水", file: "../../videos/科学/科学探索小游戏免费领/06-魔法药水.mp4",
              sec: 244, size: 16790147, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/07-看得见的声音.mp4", title: "看得见的声音", file: "../../videos/科学/科学探索小游戏免费领/07-看得见的声音.mp4",
              sec: 220, size: 18967096, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/08-变大变小的声音.mp4", title: "变大变小的声音", file: "../../videos/科学/科学探索小游戏免费领/08-变大变小的声音.mp4",
              sec: 369, size: 27455655, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/09-音调的秘密.mp4", title: "音调的秘密", file: "../../videos/科学/科学探索小游戏免费领/09-音调的秘密.mp4",
              sec: 315, size: 22010790, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/10-想潜水的乒乓球.mp4", title: "想潜水的乒乓球", file: "../../videos/科学/科学探索小游戏免费领/10-想潜水的乒乓球.mp4",
              sec: 179, size: 13323900, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/11-厉害的空气炮.mp4", title: "厉害的空气炮", file: "../../videos/科学/科学探索小游戏免费领/11-厉害的空气炮.mp4",
              sec: 328, size: 29022469, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/12-非牛顿流体.mp4", title: "非牛顿流体", file: "../../videos/科学/科学探索小游戏免费领/12-非牛顿流体.mp4",
              sec: 270, size: 18966224, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/13-会发光的钥匙链.mp4", title: "会发光的钥匙链", file: "../../videos/科学/科学探索小游戏免费领/13-会发光的钥匙链.mp4",
              sec: 394, size: 33437209, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/14-石墨电路.mp4", title: "石墨电路", file: "../../videos/科学/科学探索小游戏免费领/14-石墨电路.mp4",
              sec: 262, size: 20735896, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/科学探索小游戏免费领/15-导电橡皮泥.mp4", title: "导电橡皮泥", file: "../../videos/科学/科学探索小游戏免费领/15-导电橡皮泥.mp4",
              sec: 306, size: 26205079, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "航天知识小讲堂免费领", count: 6, seconds: 3948,
          items: [
            { id: "科学/航天知识小讲堂免费领/01-怎样才能成为航天员呢.mp4", title: "怎样才能成为航天员呢", file: "../../videos/科学/航天知识小讲堂免费领/01-怎样才能成为航天员呢.mp4",
              sec: 787, size: 65472962, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/航天知识小讲堂免费领/02-太空离我们有多远.mp4", title: "太空离我们有多远", file: "../../videos/科学/航天知识小讲堂免费领/02-太空离我们有多远.mp4",
              sec: 598, size: 50628802, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/航天知识小讲堂免费领/03-去太空的行李.mp4", title: "去太空的行李", file: "../../videos/科学/航天知识小讲堂免费领/03-去太空的行李.mp4",
              sec: 613, size: 53124734, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/航天知识小讲堂免费领/04-航天与神话.mp4", title: "航天与神话", file: "../../videos/科学/航天知识小讲堂免费领/04-航天与神话.mp4",
              sec: 568, size: 50617016, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/航天知识小讲堂免费领/05-我与航天共成长.mp4", title: "我与航天共成长", file: "../../videos/科学/航天知识小讲堂免费领/05-我与航天共成长.mp4",
              sec: 657, size: 57282447, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "科学/航天知识小讲堂免费领/06-心怀宇宙的人们.mp4", title: "心怀宇宙的人们", file: "../../videos/科学/航天知识小讲堂免费领/06-心怀宇宙的人们.mp4",
              sec: 725, size: 60741782, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        }
      ]
    },
    {
      name: "艺术", emoji: "🎨", color: "#ec4899",
      count: 49, seconds: 13579,
      series: [
        { name: "5天看懂世界TOP名画免费领", count: 5, seconds: 1522,
          items: [
            { id: "艺术/5天看懂世界TOP名画免费领/01-凡高的《向日葵》.mp4", title: "凡高的《向日葵》", file: "../../videos/艺术/5天看懂世界TOP名画免费领/01-凡高的《向日葵》.mp4",
              sec: 325, size: 44169788, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/5天看懂世界TOP名画免费领/02-《蒙娜丽莎》的微笑.mp4", title: "《蒙娜丽莎》的微笑", file: "../../videos/艺术/5天看懂世界TOP名画免费领/02-《蒙娜丽莎》的微笑.mp4",
              sec: 266, size: 36197907, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/5天看懂世界TOP名画免费领/03-康定斯基的抽象画.mp4", title: "康定斯基的抽象画", file: "../../videos/艺术/5天看懂世界TOP名画免费领/03-康定斯基的抽象画.mp4",
              sec: 284, size: 27712092, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/5天看懂世界TOP名画免费领/04-莫奈的《日出·印象》.mp4", title: "莫奈的《日出·印象》", file: "../../videos/艺术/5天看懂世界TOP名画免费领/04-莫奈的《日出·印象》.mp4",
              sec: 265, size: 34961137, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/5天看懂世界TOP名画免费领/05-马蒂斯的剪纸画.mp4", title: "马蒂斯的剪纸画", file: "../../videos/艺术/5天看懂世界TOP名画免费领/05-马蒂斯的剪纸画.mp4",
              sec: 382, size: 30623577, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "创意手绘十二生肖（免费领）", count: 6, seconds: 1474,
          items: [
            { id: "艺术/创意手绘十二生肖（免费领）/01-几何图形画12生肖.mp4", title: "几何图形画12生肖", file: "../../videos/艺术/创意手绘十二生肖（免费领）/01-几何图形画12生肖.mp4",
              sec: 209, size: 15961398, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/创意手绘十二生肖（免费领）/02-几何图形画12生肖.mp4", title: "几何图形画12生肖", file: "../../videos/艺术/创意手绘十二生肖（免费领）/02-几何图形画12生肖.mp4",
              sec: 241, size: 20256051, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/创意手绘十二生肖（免费领）/03-几何图形画12生肖.mp4", title: "几何图形画12生肖", file: "../../videos/艺术/创意手绘十二生肖（免费领）/03-几何图形画12生肖.mp4",
              sec: 269, size: 23709672, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/创意手绘十二生肖（免费领）/04-几何图形画12生肖.mp4", title: "几何图形画12生肖", file: "../../videos/艺术/创意手绘十二生肖（免费领）/04-几何图形画12生肖.mp4",
              sec: 282, size: 24140183, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/创意手绘十二生肖（免费领）/05-几何图形画12生肖.mp4", title: "几何图形画12生肖", file: "../../videos/艺术/创意手绘十二生肖（免费领）/05-几何图形画12生肖.mp4",
              sec: 233, size: 20952407, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/创意手绘十二生肖（免费领）/06-几何图形画12生肖.mp4", title: "几何图形画12生肖", file: "../../videos/艺术/创意手绘十二生肖（免费领）/06-几何图形画12生肖.mp4",
              sec: 240, size: 23529240, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "古典音乐鉴赏免费领", count: 10, seconds: 2824,
          items: [
            { id: "艺术/古典音乐鉴赏免费领/01-优雅的“乐器皇后”.mp4", title: "优雅的“乐器皇后”", file: "../../videos/艺术/古典音乐鉴赏免费领/01-优雅的“乐器皇后”.mp4",
              sec: 343, size: 27266416, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/古典音乐鉴赏免费领/02-《g小调第四十号交响曲》.mp4", title: "《g小调第四十号交响曲》", file: "../../videos/艺术/古典音乐鉴赏免费领/02-《g小调第四十号交响曲》.mp4",
              sec: 348, size: 25299773, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/古典音乐鉴赏免费领/03-闪亮的“魔法棒”.mp4", title: "闪亮的“魔法棒”", file: "../../videos/艺术/古典音乐鉴赏免费领/03-闪亮的“魔法棒”.mp4",
              sec: 278, size: 20770134, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/古典音乐鉴赏免费领/04-《芦笛舞曲》.mp4", title: "《芦笛舞曲》", file: "../../videos/艺术/古典音乐鉴赏免费领/04-《芦笛舞曲》.mp4",
              sec: 203, size: 13267148, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/古典音乐鉴赏免费领/05-金灿灿的“号角”.mp4", title: "金灿灿的“号角”", file: "../../videos/艺术/古典音乐鉴赏免费领/05-金灿灿的“号角”.mp4",
              sec: 312, size: 27574466, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/古典音乐鉴赏免费领/06-《威廉退尔序曲》.mp4", title: "《威廉退尔序曲》", file: "../../videos/艺术/古典音乐鉴赏免费领/06-《威廉退尔序曲》.mp4",
              sec: 270, size: 21549650, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/古典音乐鉴赏免费领/07-节奏中的“指挥家”.mp4", title: "节奏中的“指挥家”", file: "../../videos/艺术/古典音乐鉴赏免费领/07-节奏中的“指挥家”.mp4",
              sec: 304, size: 25037790, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/古典音乐鉴赏免费领/08-《布基上校进行曲》.mp4", title: "《布基上校进行曲》", file: "../../videos/艺术/古典音乐鉴赏免费领/08-《布基上校进行曲》.mp4",
              sec: 249, size: 27753880, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/古典音乐鉴赏免费领/09-古典乐器“大派对”.mp4", title: "古典乐器“大派对”", file: "../../videos/艺术/古典音乐鉴赏免费领/09-古典乐器“大派对”.mp4",
              sec: 260, size: 27777851, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/古典音乐鉴赏免费领/10-《电闪雷鸣波尔卡》.mp4", title: "《电闪雷鸣波尔卡》", file: "../../videos/艺术/古典音乐鉴赏免费领/10-《电闪雷鸣波尔卡》.mp4",
              sec: 257, size: 15497864, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "孩子可以唱跳的古典乐免费领", count: 6, seconds: 2298,
          items: [
            { id: "艺术/孩子可以唱跳的古典乐免费领/01-斑马音乐介绍.mp4", title: "斑马音乐介绍", file: "../../videos/艺术/孩子可以唱跳的古典乐免费领/01-斑马音乐介绍.mp4",
              sec: 103, size: 6438816, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/孩子可以唱跳的古典乐免费领/02-热情的民间舞曲.mp4", title: "热情的民间舞曲", file: "../../videos/艺术/孩子可以唱跳的古典乐免费领/02-热情的民间舞曲.mp4",
              sec: 437, size: 30029452, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/孩子可以唱跳的古典乐免费领/03-温柔的小夜曲.mp4", title: "温柔的小夜曲", file: "../../videos/艺术/孩子可以唱跳的古典乐免费领/03-温柔的小夜曲.mp4",
              sec: 454, size: 33029014, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/孩子可以唱跳的古典乐免费领/04-慷慨的进行曲.mp4", title: "慷慨的进行曲", file: "../../videos/艺术/孩子可以唱跳的古典乐免费领/04-慷慨的进行曲.mp4",
              sec: 397, size: 29025624, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/孩子可以唱跳的古典乐免费领/05-抒情的圆舞曲.mp4", title: "抒情的圆舞曲", file: "../../videos/艺术/孩子可以唱跳的古典乐免费领/05-抒情的圆舞曲.mp4",
              sec: 484, size: 39414025, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/孩子可以唱跳的古典乐免费领/06-欢乐的爵士乐.mp4", title: "欢乐的爵士乐", file: "../../videos/艺术/孩子可以唱跳的古典乐免费领/06-欢乐的爵士乐.mp4",
              sec: 423, size: 33678127, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "绘画材料大发现免费领", count: 5, seconds: 1657,
          items: [
            { id: "艺术/绘画材料大发现免费领/01-鸡蛋盒变小老鼠.mp4", title: "鸡蛋盒变小老鼠", file: "../../videos/艺术/绘画材料大发现免费领/01-鸡蛋盒变小老鼠.mp4",
              sec: 316, size: 38578908, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/绘画材料大发现免费领/02-纸箱变城市.mp4", title: "纸箱变城市", file: "../../videos/艺术/绘画材料大发现免费领/02-纸箱变城市.mp4",
              sec: 372, size: 38068321, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/绘画材料大发现免费领/03-牛奶盒变校车.mp4", title: "牛奶盒变校车", file: "../../videos/艺术/绘画材料大发现免费领/03-牛奶盒变校车.mp4",
              sec: 308, size: 32454443, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/绘画材料大发现免费领/04-五颜六色的叶子.mp4", title: "五颜六色的叶子", file: "../../videos/艺术/绘画材料大发现免费领/04-五颜六色的叶子.mp4",
              sec: 307, size: 46187703, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/绘画材料大发现免费领/05-石头上的小昆虫.mp4", title: "石头上的小昆虫", file: "../../videos/艺术/绘画材料大发现免费领/05-石头上的小昆虫.mp4",
              sec: 354, size: 54517574, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "音乐入门·0基础学五线谱（免费领）", count: 17, seconds: 3804,
          items: [
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/01-D1 认识五线谱.mp4", title: "D1 认识五线谱", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/01-D1 认识五线谱.mp4",
              sec: 302, size: 15293415, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/02-D2 认识五线谱的线和间.mp4", title: "D2 认识五线谱的线和间", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/02-D2 认识五线谱的线和间.mp4",
              sec: 261, size: 12435268, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/03-D3 认识音符do.mp4", title: "D3 认识音符do", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/03-D3 认识音符do.mp4",
              sec: 186, size: 9263687, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/04-D4 认识音符re.mp4", title: "D4 认识音符re", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/04-D4 认识音符re.mp4",
              sec: 151, size: 7997832, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/05-D5 演唱《火车开啦》.mp4", title: "D5 演唱《火车开啦》", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/05-D5 演唱《火车开啦》.mp4",
              sec: 197, size: 9202747, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/06-D6 认识音符mi.mp4", title: "D6 认识音符mi", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/06-D6 认识音符mi.mp4",
              sec: 187, size: 9079113, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/07-D7 演唱《热面包》.mp4", title: "D7 演唱《热面包》", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/07-D7 演唱《热面包》.mp4",
              sec: 235, size: 9813560, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/08-D8 认识音符fa.mp4", title: "D8 认识音符fa", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/08-D8 认识音符fa.mp4",
              sec: 195, size: 9090120, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/09-D9 演唱《王老先生有块地》.mp4", title: "D9 演唱《王老先生有块地》", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/09-D9 演唱《王老先生有块地》.mp4",
              sec: 211, size: 10012197, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/10-D10 认识音符sol.mp4", title: "D10 认识音符sol", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/10-D10 认识音符sol.mp4",
              sec: 165, size: 8760569, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/11-D11 演唱《粉刷匠》.mp4", title: "D11 演唱《粉刷匠》", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/11-D11 演唱《粉刷匠》.mp4",
              sec: 235, size: 9755933, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/12-D12 认识音符la.mp4", title: "D12 认识音符la", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/12-D12 认识音符la.mp4",
              sec: 182, size: 8208977, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/13-D13 演唱《小星星》.mp4", title: "D13 演唱《小星星》", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/13-D13 演唱《小星星》.mp4",
              sec: 438, size: 15191140, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/14-D14 认识音符si.mp4", title: "D14 认识音符si", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/14-D14 认识音符si.mp4",
              sec: 167, size: 8554776, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/15-D15 演唱《玛丽有只小羊羔》.mp4", title: "D15 演唱《玛丽有只小羊羔》", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/15-D15 演唱《玛丽有只小羊羔》.mp4",
              sec: 232, size: 8597636, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/16-D16 认识音符 高音do'.mp4", title: "D16 认识音符 高音do'", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/16-D16 认识音符 高音do'.mp4",
              sec: 209, size: 9224924, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "艺术/音乐入门·0基础学五线谱（免费领）/17-D17 演唱《划船歌》.mp4", title: "D17 演唱《划船歌》", file: "../../videos/艺术/音乐入门·0基础学五线谱（免费领）/17-D17 演唱《划船歌》.mp4",
              sec: 251, size: 9744593, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        }
      ]
    },
    {
      name: "综合", emoji: "🌈", color: "#64748b",
      count: 62, seconds: 24492,
      series: [
        { name: "30天幼升小入学启蒙必备", count: 56, seconds: 22123,
          items: [
            { id: "综合/30天幼升小入学启蒙必备/01-小演员请就位.mp4", title: "小演员请就位", file: "../../videos/综合/30天幼升小入学启蒙必备/01-小演员请就位.mp4",
              sec: 605, size: 30323335, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/02-甜品派对.mp4", title: "甜品派对", file: "../../videos/综合/30天幼升小入学启蒙必备/02-甜品派对.mp4",
              sec: 528, size: 23080774, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/03-巧克力爆发啦.mp4", title: "巧克力爆发啦", file: "../../videos/综合/30天幼升小入学启蒙必备/03-巧克力爆发啦.mp4",
              sec: 529, size: 24147257, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/04-造雪大作战.mp4", title: "造雪大作战", file: "../../videos/综合/30天幼升小入学启蒙必备/04-造雪大作战.mp4",
              sec: 536, size: 27253808, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/05-废品回收机.mp4", title: "废品回收机", file: "../../videos/综合/30天幼升小入学启蒙必备/05-废品回收机.mp4",
              sec: 736, size: 36510528, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/06-会旋转的风筝.mp4", title: "会旋转的风筝", file: "../../videos/综合/30天幼升小入学启蒙必备/06-会旋转的风筝.mp4",
              sec: 610, size: 25689240, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/07-暴雨大作战.mp4", title: "暴雨大作战", file: "../../videos/综合/30天幼升小入学启蒙必备/07-暴雨大作战.mp4",
              sec: 559, size: 25228873, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/08-山羊爷爷的树屋.mp4", title: "山羊爷爷的树屋", file: "../../videos/综合/30天幼升小入学启蒙必备/08-山羊爷爷的树屋.mp4",
              sec: 492, size: 24349543, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/09-神秘的小帮手.mp4", title: "神秘的小帮手", file: "../../videos/综合/30天幼升小入学启蒙必备/09-神秘的小帮手.mp4",
              sec: 490, size: 23142516, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/10-趣味运动会.mp4", title: "趣味运动会", file: "../../videos/综合/30天幼升小入学启蒙必备/10-趣味运动会.mp4",
              sec: 686, size: 32883090, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/11-小小美食家（上）.mp4", title: "小小美食家（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/11-小小美食家（上）.mp4",
              sec: 314, size: 15280205, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/12-小小美食家（下）.mp4", title: "小小美食家（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/12-小小美食家（下）.mp4",
              sec: 299, size: 14468945, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/13-我喜欢逛超市（上）.mp4", title: "我喜欢逛超市（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/13-我喜欢逛超市（上）.mp4",
              sec: 270, size: 13488484, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/14-我喜欢逛超市（下）.mp4", title: "我喜欢逛超市（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/14-我喜欢逛超市（下）.mp4",
              sec: 300, size: 15745243, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/15-感受四季（上）.mp4", title: "感受四季（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/15-感受四季（上）.mp4",
              sec: 372, size: 18863495, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/16-感受四季（下）.mp4", title: "感受四季（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/16-感受四季（下）.mp4",
              sec: 285, size: 15414570, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/17-丰富的课余活动（上）.mp4", title: "丰富的课余活动（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/17-丰富的课余活动（上）.mp4",
              sec: 266, size: 22875347, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/18-丰富的课余生活（下）.mp4", title: "丰富的课余生活（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/18-丰富的课余生活（下）.mp4",
              sec: 294, size: 25689766, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/19-体验校园生活（上）.mp4", title: "体验校园生活（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/19-体验校园生活（上）.mp4",
              sec: 346, size: 35151973, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/20-体验校园生活（下）.mp4", title: "体验校园生活（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/20-体验校园生活（下）.mp4",
              sec: 305, size: 32472229, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/21-公园游记（上）.mp4", title: "公园游记（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/21-公园游记（上）.mp4",
              sec: 261, size: 15325646, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/22-公园游记（下）.mp4", title: "公园游记（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/22-公园游记（下）.mp4",
              sec: 248, size: 15073584, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/23-八斗的画室（上）.mp4", title: "八斗的画室（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/23-八斗的画室（上）.mp4",
              sec: 346, size: 21460306, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/24-八斗的画室（下）.mp4", title: "八斗的画室（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/24-八斗的画室（下）.mp4",
              sec: 314, size: 17509654, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/25-我和我的家人（上）.mp4", title: "我和我的家人（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/25-我和我的家人（上）.mp4",
              sec: 293, size: 17783997, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/26-我和我的家人（下）.mp4", title: "我和我的家人（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/26-我和我的家人（下）.mp4",
              sec: 303, size: 17618705, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/27-森林探险记（上）.mp4", title: "森林探险记（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/27-森林探险记（上）.mp4",
              sec: 362, size: 20523523, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/28-森林探险记（下）.mp4", title: "森林探险记（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/28-森林探险记（下）.mp4",
              sec: 346, size: 19369264, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/29-我和我的家乡（上）.mp4", title: "我和我的家乡（上）", file: "../../videos/综合/30天幼升小入学启蒙必备/29-我和我的家乡（上）.mp4",
              sec: 337, size: 19541009, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/30-我和我的家乡（下）.mp4", title: "我和我的家乡（下）", file: "../../videos/综合/30天幼升小入学启蒙必备/30-我和我的家乡（下）.mp4",
              sec: 353, size: 16540569, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/31-Big A, Little a.mp4", title: "Big A, Little a", file: "../../videos/综合/30天幼升小入学启蒙必备/31-Big A, Little a.mp4",
              sec: 412, size: 24264240, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/32-Big B, Little b.mp4", title: "Big B, Little b", file: "../../videos/综合/30天幼升小入学启蒙必备/32-Big B, Little b.mp4",
              sec: 367, size: 21901454, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/33-Big C, Little c.mp4", title: "Big C, Little c", file: "../../videos/综合/30天幼升小入学启蒙必备/33-Big C, Little c.mp4",
              sec: 386, size: 25243691, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/34-Big D, Little d.mp4", title: "Big D, Little d", file: "../../videos/综合/30天幼升小入学启蒙必备/34-Big D, Little d.mp4",
              sec: 394, size: 25476939, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/35-Big E, Little e.mp4", title: "Big E, Little e", file: "../../videos/综合/30天幼升小入学启蒙必备/35-Big E, Little e.mp4",
              sec: 361, size: 22263688, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/36-Big F, Little f.mp4", title: "Big F, Little f", file: "../../videos/综合/30天幼升小入学启蒙必备/36-Big F, Little f.mp4",
              sec: 361, size: 22148109, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/37-Big G, Little g.mp4", title: "Big G, Little g", file: "../../videos/综合/30天幼升小入学启蒙必备/37-Big G, Little g.mp4",
              sec: 360, size: 23469867, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/38-Big H, Little h.mp4", title: "Big H, Little h", file: "../../videos/综合/30天幼升小入学启蒙必备/38-Big H, Little h.mp4",
              sec: 344, size: 21921834, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/39-Big I, Little i.mp4", title: "Big I, Little i", file: "../../videos/综合/30天幼升小入学启蒙必备/39-Big I, Little i.mp4",
              sec: 447, size: 28939526, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/40-Big J, Little j.mp4", title: "Big J, Little j", file: "../../videos/综合/30天幼升小入学启蒙必备/40-Big J, Little j.mp4",
              sec: 374, size: 23785307, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/41-Big K, Little k.mp4", title: "Big K, Little k", file: "../../videos/综合/30天幼升小入学启蒙必备/41-Big K, Little k.mp4",
              sec: 377, size: 24753368, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/42-Big L, Little l.mp4", title: "Big L, Little l", file: "../../videos/综合/30天幼升小入学启蒙必备/42-Big L, Little l.mp4",
              sec: 365, size: 22865205, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/43-Big M, Little m.mp4", title: "Big M, Little m", file: "../../videos/综合/30天幼升小入学启蒙必备/43-Big M, Little m.mp4",
              sec: 364, size: 23429275, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/44-Big N, Little n.mp4", title: "Big N, Little n", file: "../../videos/综合/30天幼升小入学启蒙必备/44-Big N, Little n.mp4",
              sec: 379, size: 25433287, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/45-Big O, Little o.mp4", title: "Big O, Little o", file: "../../videos/综合/30天幼升小入学启蒙必备/45-Big O, Little o.mp4",
              sec: 370, size: 24954416, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/46-Big P, Little p.mp4", title: "Big P, Little p", file: "../../videos/综合/30天幼升小入学启蒙必备/46-Big P, Little p.mp4",
              sec: 392, size: 24994309, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/47-Big Q, Little q.mp4", title: "Big Q, Little q", file: "../../videos/综合/30天幼升小入学启蒙必备/47-Big Q, Little q.mp4",
              sec: 391, size: 25853379, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/48-Big R, Little r.mp4", title: "Big R, Little r", file: "../../videos/综合/30天幼升小入学启蒙必备/48-Big R, Little r.mp4",
              sec: 401, size: 26375219, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/49-Big S, Little s.mp4", title: "Big S, Little s", file: "../../videos/综合/30天幼升小入学启蒙必备/49-Big S, Little s.mp4",
              sec: 396, size: 28278710, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/50-Big T, Little t.mp4", title: "Big T, Little t", file: "../../videos/综合/30天幼升小入学启蒙必备/50-Big T, Little t.mp4",
              sec: 420, size: 28941649, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/51-Big U, Little u.mp4", title: "Big U, Little u", file: "../../videos/综合/30天幼升小入学启蒙必备/51-Big U, Little u.mp4",
              sec: 392, size: 27127136, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/52-Big V, Little v.mp4", title: "Big V, Little v", file: "../../videos/综合/30天幼升小入学启蒙必备/52-Big V, Little v.mp4",
              sec: 437, size: 29487718, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/53-Big W, Little w.mp4", title: "Big W, Little w", file: "../../videos/综合/30天幼升小入学启蒙必备/53-Big W, Little w.mp4",
              sec: 436, size: 29130835, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/54-Big X, Little x.mp4", title: "Big X, Little x", file: "../../videos/综合/30天幼升小入学启蒙必备/54-Big X, Little x.mp4",
              sec: 431, size: 29567626, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/55-Big Y, Little y.mp4", title: "Big Y, Little y", file: "../../videos/综合/30天幼升小入学启蒙必备/55-Big Y, Little y.mp4",
              sec: 393, size: 26465031, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/30天幼升小入学启蒙必备/56-Big Z, Little z.mp4", title: "Big Z, Little z", file: "../../videos/综合/30天幼升小入学启蒙必备/56-Big Z, Little z.mp4",
              sec: 388, size: 27650835, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "家庭情绪管理全攻略免费领", count: 5, seconds: 1764,
          items: [
            { id: "综合/家庭情绪管理全攻略免费领/01-第1节 如何营造良好的家庭氛围.mp4", title: "第1节 如何营造良好的家庭氛围", file: "../../videos/综合/家庭情绪管理全攻略免费领/01-第1节 如何营造良好的家庭氛围.mp4",
              sec: 344, size: 20022407, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/家庭情绪管理全攻略免费领/02-第2节 各阶段儿童的情绪发展特点.mp4", title: "第2节 各阶段儿童的情绪发展特点", file: "../../videos/综合/家庭情绪管理全攻略免费领/02-第2节 各阶段儿童的情绪发展特点.mp4",
              sec: 305, size: 17946955, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/家庭情绪管理全攻略免费领/03-第3节 如何帮孩子平复强烈的情绪.mp4", title: "第3节 如何帮孩子平复强烈的情绪", file: "../../videos/综合/家庭情绪管理全攻略免费领/03-第3节 如何帮孩子平复强烈的情绪.mp4",
              sec: 354, size: 20224653, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/家庭情绪管理全攻略免费领/04-第4节 如何应对养育焦虑.mp4", title: "第4节 如何应对养育焦虑", file: "../../videos/综合/家庭情绪管理全攻略免费领/04-第4节 如何应对养育焦虑.mp4",
              sec: 372, size: 38906246, ok: true, vcodec: "avc1", acodec: "mp4a", },
            { id: "综合/家庭情绪管理全攻略免费领/05-第5节 如何培养良好社会情绪能力.mp4", title: "第5节 如何培养良好社会情绪能力", file: "../../videos/综合/家庭情绪管理全攻略免费领/05-第5节 如何培养良好社会情绪能力.mp4",
              sec: 389, size: 31950408, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        },
        { name: "", count: 1, seconds: 605,
          items: [
            { id: "综合/示例视频-10分钟.mp4", title: "示例视频-10分钟", file: "../../videos/综合/示例视频-10分钟.mp4",
              sec: 605, size: 30323335, ok: true, vcodec: "avc1", acodec: "mp4a", }
          ]
        }
      ]
    }
  ]
};
